### PR TITLE
Repo refactoring

### PR DESCRIPTION
**Pull request by jenkin**
In this branch I refactored old repository, moving all submodules on root folder, and merging new scripts and configuration fileds from daf-ckan.

Please note I removed all references to LDAP and harvesting initialization.

### CODE REVIEW

**Review by LucaPrete — APPROVED** [review]
Looks good to me. Couple of questions:
* Do we plan to split this in two repos, dati-ckan and dati-ckan-solr?
* Have you at least tried  the docker-compose?

**Comment by jenkin** [comment]
@LucaPrete 

* this repo has a submodule pointing to https://github.com/teamdigitale/daf-ckan-solr/ and builds solr image from that dockerfile because of [this issue](https://github.com/teamdigitale/daf-ckan-solr/issues/4), once we will resolve it we can use public image and remove solr submodule

* sure, all works as expected

**Comment by jenkin** [comment]
@LucaPrete ok, I fixed the first issue

**Comment by LucaPrete** [comment]
Thanks

Il giorno mar 2 lug 2019 alle 12:31 Alessio Cimarelli <
notifications@github.com> ha scritto:

**Comment by jenkin** [comment]
Sorry @LucaPrete , I notice you have many references to old geo-solutions repository and docker images I removed some commits ago (see https://github.com/italia/dati-ckan-docker/pull/36). Take a look to [these lines of dockerfile](https://github.com/italia/dati-ckan-docker/blob/43aa679426b8b35cc9bee3f536caf5211df190e5/ckan/Dockerfile#L92), for example.

I fixed this references [here](https://github.com/italia/dati-ckan-docker/pull/39/commits/ba52594bdb2ba3041cc082f7085200b91ea41c0e).

**Comment by jenkin** [comment]
Ok, I added support to named volumes in docker compose configuration to have data persistency.

**Comment by jenkin** [comment]
@LucaPrete is it possible to republish the [ckan/postgresql:latest](https://hub.docker.com/r/ckan/postgresql/tags) image on [teamdigitale/daf-ckan-postgresql:10.1](https://hub.docker.com/r/teamdigitale/daf-ckan-postgresql)? Maybe linked to a [teamdigitale/daf-ckan-postgresql](https://github.com/teamdigitale/daf-ckan-postgresql) repository as we did with solr?

**Comment by LucaPrete** [comment]
@jenkin can we try to contact CKAN people first to ask them to properly tag versions? :) I would avoid to copy and paste the content of a repo just for this goal..

**Review by LucaPrete — APPROVED** [review]

**Pull request merged**
